export enum RequestStatus {
  SUCCESS = 200,
  FORBIDDEN = 403,
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  INVALID_CREDINTIALS = 'INVALID_CREDINTIALS',
  NEED_UPDATE_PASSWORD = 'NEED_UPDATE_PASSWORD',
  PASSWORDS_DONT_MATCH = 'PASSWORDS_DONT_MATCH'
}
