export const SIGN_IN_SET_INPUT = 'SIGN_IN_SET_INPUT';
export const SIGN_IN_TOGGLE_CONFIRMED = 'SIGN_IN_TOGGLE_CONFIRMED';
export const CLEAR_SIGNIN_ERROR = 'CLEAR_SIGNIN_ERROR';
export const SIGN_IN_LOGOUT = 'SIGN_IN_LOGOUT';
export const SIGN_IN_NEED_UPDATE_PASSWORD = 'SIGN_IN_NEED_UPDATE_PASSWORD';
