export const SET_ACTIVE_TAB_ID = 'SET_ACTIVE_TAB_ID';
export const SET_FIELD_VALUE = 'SET_FIELD_VALUE';
export const VALIDATE_FIELD = 'VALIDATE_FIELD';
export const VALIDATE_TAB_FIELDS = 'VALIDATE_TAB_FIELDS';
// export const VALIDATE_ALL_FIELDS = 'VALIDATE_ALL_FIELDS';
